library(dplyr)
mecha <- read.csv("MechaCar_mpg.csv", check.names=F,stringsAsFactors = F)
summarize(mecha)
mecha_multiple <- lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mecha)
summary(mecha_multiple)
